### PR TITLE
Optimize ascii.validPrint

### PR DESCRIPTION
**Pull request by achille-roussel**
This PR is the result of an experiment I ran, converting the `ascii.validPrint` implementation from Go to assembly. It turned out that the hybrid approach of using Go for short strings, and delegating to the assembly version (using SSE instructions) for longer strings seems to provide the best results; otherwise, the pure assembly implementation was somehow ~20% slower on small strings (I didn't dig deep into why, we're already in good-enough land for short strings).

This optimization is especially useful in cases where we are decoding strings that are base64 encoded (usually going in a `[]byte` field), and tend to embed opaque and lengthy data.

```
name                                old time/op    new time/op     delta
ValidPrint/#00                        2.08ns ± 4%     2.02ns ± 3%     ~     (p=0.063 n=5+5)
ValidPrint/hello                      6.30ns ± 2%     5.70ns ± 1%   -9.62%  (p=0.008 n=5+5)
ValidPrint/Hello_World!               6.63ns ± 3%     6.16ns ± 2%   -7.12%  (p=0.008 n=5+5)
ValidPrint/H~llo_World!               6.52ns ± 2%     6.10ns ± 2%   -6.53%  (p=0.008 n=5+5)
ValidPrint/H~llo                      6.34ns ± 1%     5.64ns ± 2%  -11.16%  (p=0.008 n=5+5)
ValidPrint/你好                         5.81ns ± 3%     5.19ns ± 5%  -10.71%  (p=0.008 n=5+5)
ValidPrint/~                          6.17ns ± 2%     5.07ns ± 2%  -17.88%  (p=0.008 n=5+5)
ValidPrint/�                          6.30ns ± 2%     5.08ns ± 3%  -19.28%  (p=0.008 n=5+5)
ValidPrint/\u007f                     6.13ns ± 2%     5.22ns ± 1%  -14.82%  (p=0.008 n=5+5)
ValidPrint/�#01                       5.93ns ± 1%     5.17ns ± 2%  -12.75%  (p=0.008 n=5+5)
ValidPrint/some_kind_of_long...       13.9ns ± 3%     13.0ns ± 4%   -6.47%  (p=0.016 n=5+5)
ValidPrint/some_kind_of_long...#01    13.5ns ± 1%     10.2ns ± 0%  -24.22%  (p=0.000 n=5+4)
ValidPrint/12345678901234567...       1.13µs ± 1%     0.69µs ± 2%  -38.60%  (p=0.008 n=5+5)

name                                old speed      new speed       delta
ValidPrint/hello                     793MB/s ± 2%    878MB/s ± 1%  +10.67%  (p=0.008 n=5+5)
ValidPrint/Hello_World!             1.81GB/s ± 3%   1.95GB/s ± 2%   +7.66%  (p=0.008 n=5+5)
ValidPrint/H~llo_World!             1.84GB/s ± 2%   1.97GB/s ± 2%   +7.00%  (p=0.008 n=5+5)
ValidPrint/H~llo                     789MB/s ± 2%    887MB/s ± 2%  +12.50%  (p=0.008 n=5+5)
ValidPrint/你好                       1.03GB/s ± 3%   1.16GB/s ± 5%  +12.06%  (p=0.008 n=5+5)
ValidPrint/~                         162MB/s ± 3%    197MB/s ± 2%  +21.75%  (p=0.008 n=5+5)
ValidPrint/�                         159MB/s ± 2%    197MB/s ± 3%  +23.85%  (p=0.008 n=5+5)
ValidPrint/\u007f                    163MB/s ± 2%    191MB/s ± 1%  +17.30%  (p=0.008 n=5+5)
ValidPrint/�#01                      169MB/s ± 1%    193MB/s ± 2%  +14.65%  (p=0.008 n=5+5)
ValidPrint/some_kind_of_long...     3.74GB/s ± 3%   4.00GB/s ± 4%   +6.91%  (p=0.016 n=5+5)
ValidPrint/some_kind_of_long...#01  4.75GB/s ± 1%   6.27GB/s ± 1%  +31.88%  (p=0.008 n=5+5)
ValidPrint/12345678901234567...     8.87GB/s ± 2%  14.45GB/s ± 2%  +62.93%  (p=0.008 n=5+5)
```

### CODE REVIEW

**Review by chriso — APPROVED** [review]
Probably overkill, but AVX2 has VPMINUP/VPMAXUB/VPCMPEQB you could use instead of trying to port the SWAR technique to SIMD.

You could VPMAXUB 32x bytes with 0x20 and then check with VPCMPEQB whether any aren't equal to 0x20. Then do the same on the upper end with VPMINUB and 0x7E.

**Comment by chriso** [comment]
The LLVM `-03 -march=native` result for me is a little more convoluted 😅 

```c
#include <stddef.h>
#include <stdint.h>

int simd_ascii_print(const uint8_t* src, size_t size) {
    int valid = 1;
    for (size_t i = 0; i < size; i++) {
        valid &= src[i] >= 0x20 && src[i] <= 0x7E;
    }
    return valid;
}
```

```objdump
0000000000000000 _simd_ascii_print:
       0: 55                           	pushq	%rbp
       1: 48 89 e5                     	movq	%rsp, %rbp
       4: 48 85 f6                     	testq	%rsi, %rsi
       7: 74 13                        	je	19 <_simd_ascii_print+0x1c>
       9: 48 83 fe 1f                  	cmpq	$31, %rsi
       d: 77 14                        	ja	20 <_simd_ascii_print+0x23>
       f: b8 01 00 00 00               	movl	$1, %eax
      14: 45 31 c9                     	xorl	%r9d, %r9d
      17: e9 74 02 00 00               	jmp	628 <_simd_ascii_print+0x290>
      1c: b8 01 00 00 00               	movl	$1, %eax
      21: 5d                           	popq	%rbp
      22: c3                           	retq
      23: 49 89 f1                     	movq	%rsi, %r9
      26: 49 83 e1 e0                  	andq	$-32, %r9
      2a: 49 8d 41 e0                  	leaq	-32(%r9), %rax
      2e: 48 89 c2                     	movq	%rax, %rdx
      31: 48 c1 ea 05                  	shrq	$5, %rdx
      35: 48 ff c2                     	incq	%rdx
      38: 41 89 d0                     	movl	%edx, %r8d
      3b: 41 83 e0 01                  	andl	$1, %r8d
      3f: 48 85 c0                     	testq	%rax, %rax
      42: 0f 84 67 02 00 00            	je	615 <_simd_ascii_print+0x2af>
      48: 4c 29 c2                     	subq	%r8, %rdx
      4b: c4 41 35 76 c9               	vpcmpeqd	%ymm9, %ymm9, %ymm9
      50: c5 7d 6f 05 88 02 00 00      	vmovdqa	648(%rip), %ymm8
      58: 31 c0                        	xorl	%eax, %eax
      5a: c5 79 6f 25 9e 02 00 00      	vmovdqa	670(%rip), %xmm12
      62: c5 79 6f 2d a6 02 00 00      	vmovdqa	678(%rip), %xmm13
      6a: c4 41 09 76 f6               	vpcmpeqd	%xmm14, %xmm14, %xmm14
      6f: c4 62 7d 58 3d a8 02 00 00   	vpbroadcastd	680(%rip), %ymm15
      78: c4 41 2d 76 d2               	vpcmpeqd	%ymm10, %ymm10, %ymm10
      7d: c4 41 25 76 db               	vpcmpeqd	%ymm11, %ymm11, %ymm11
      82: 66 2e 0f 1f 84 00 00 00 00 00	nopw	%cs:(%rax,%rax)
      8c: 0f 1f 40 00                  	nopl	(%rax)
      90: c5 fa 7e 04 07               	vmovq	(%rdi,%rax), %xmm0
      95: c5 fa 7e 4c 07 08            	vmovq	8(%rdi,%rax), %xmm1
      9b: c5 fa 7e 54 07 10            	vmovq	16(%rdi,%rax), %xmm2
      a1: c5 fa 7e 5c 07 18            	vmovq	24(%rdi,%rax), %xmm3
      a7: c5 99 fc c0                  	vpaddb	%xmm0, %xmm12, %xmm0
      ab: c5 99 fc c9                  	vpaddb	%xmm1, %xmm12, %xmm1
      af: c5 99 fc d2                  	vpaddb	%xmm2, %xmm12, %xmm2
      b3: c5 99 fc db                  	vpaddb	%xmm3, %xmm12, %xmm3
      b7: c5 91 de e0                  	vpmaxub	%xmm0, %xmm13, %xmm4
      bb: c5 f9 74 c4                  	vpcmpeqb	%xmm4, %xmm0, %xmm0
      bf: c5 89 ef c0                  	vpxor	%xmm0, %xmm14, %xmm0
      c3: c4 e2 7d 31 c0               	vpmovzxbd	%xmm0, %ymm0
      c8: c5 bd db c0                  	vpand	%ymm0, %ymm8, %ymm0
      cc: c5 91 de e1                  	vpmaxub	%xmm1, %xmm13, %xmm4
      d0: c5 f1 74 cc                  	vpcmpeqb	%xmm4, %xmm1, %xmm1
      d4: c5 89 ef c9                  	vpxor	%xmm1, %xmm14, %xmm1
      d8: c4 e2 7d 31 c9               	vpmovzxbd	%xmm1, %ymm1
      dd: c5 b5 db c9                  	vpand	%ymm1, %ymm9, %ymm1
      e1: c5 91 de e2                  	vpmaxub	%xmm2, %xmm13, %xmm4
      e5: c5 e9 74 d4                  	vpcmpeqb	%xmm4, %xmm2, %xmm2
      e9: c5 89 ef d2                  	vpxor	%xmm2, %xmm14, %xmm2
      ed: c4 e2 7d 31 d2               	vpmovzxbd	%xmm2, %ymm2
      f2: c5 ad db d2                  	vpand	%ymm2, %ymm10, %ymm2
      f6: c5 91 de e3                  	vpmaxub	%xmm3, %xmm13, %xmm4
      fa: c5 e1 74 dc                  	vpcmpeqb	%xmm4, %xmm3, %xmm3
      fe: c5 89 ef db                  	vpxor	%xmm3, %xmm14, %xmm3
     102: c4 e2 7d 31 db               	vpmovzxbd	%xmm3, %ymm3
     107: c5 25 db db                  	vpand	%ymm3, %ymm11, %ymm11
     10b: c5 fa 7e 64 07 20            	vmovq	32(%rdi,%rax), %xmm4
     111: c5 fa 7e 6c 07 28            	vmovq	40(%rdi,%rax), %xmm5
     117: c5 fa 7e 74 07 30            	vmovq	48(%rdi,%rax), %xmm6
     11d: c5 fa 7e 7c 07 38            	vmovq	56(%rdi,%rax), %xmm7
     123: c5 99 fc e4                  	vpaddb	%xmm4, %xmm12, %xmm4
     127: c5 99 fc ed                  	vpaddb	%xmm5, %xmm12, %xmm5
     12b: c5 99 fc f6                  	vpaddb	%xmm6, %xmm12, %xmm6
     12f: c5 99 fc ff                  	vpaddb	%xmm7, %xmm12, %xmm7
     133: c5 91 de dc                  	vpmaxub	%xmm4, %xmm13, %xmm3
     137: c5 d9 74 db                  	vpcmpeqb	%xmm3, %xmm4, %xmm3
     13b: c5 89 ef db                  	vpxor	%xmm3, %xmm14, %xmm3
     13f: c4 e2 7d 31 db               	vpmovzxbd	%xmm3, %ymm3
     144: c5 85 db db                  	vpand	%ymm3, %ymm15, %ymm3
     148: c5 7d db c3                  	vpand	%ymm3, %ymm0, %ymm8
     14c: c5 91 de c5                  	vpmaxub	%xmm5, %xmm13, %xmm0
     150: c5 d1 74 c0                  	vpcmpeqb	%xmm0, %xmm5, %xmm0
     154: c5 89 ef c0                  	vpxor	%xmm0, %xmm14, %xmm0
     158: c4 e2 7d 31 c0               	vpmovzxbd	%xmm0, %ymm0
     15d: c5 85 db c0                  	vpand	%ymm0, %ymm15, %ymm0
     161: c5 75 db c8                  	vpand	%ymm0, %ymm1, %ymm9
     165: c5 91 de c6                  	vpmaxub	%xmm6, %xmm13, %xmm0
     169: c5 c9 74 c0                  	vpcmpeqb	%xmm0, %xmm6, %xmm0
     16d: c5 89 ef c0                  	vpxor	%xmm0, %xmm14, %xmm0
     171: c4 e2 7d 31 c0               	vpmovzxbd	%xmm0, %ymm0
     176: c5 85 db c0                  	vpand	%ymm0, %ymm15, %ymm0
     17a: c5 6d db d0                  	vpand	%ymm0, %ymm2, %ymm10
     17e: c5 91 de c7                  	vpmaxub	%xmm7, %xmm13, %xmm0
     182: c5 c1 74 c0                  	vpcmpeqb	%xmm0, %xmm7, %xmm0
     186: c5 89 ef c0                  	vpxor	%xmm0, %xmm14, %xmm0
     18a: c4 e2 7d 31 c0               	vpmovzxbd	%xmm0, %ymm0
     18f: c5 85 db c0                  	vpand	%ymm0, %ymm15, %ymm0
     193: c5 25 db d8                  	vpand	%ymm0, %ymm11, %ymm11
     197: 48 83 c0 40                  	addq	$64, %rax
     19b: 48 83 c2 fe                  	addq	$-2, %rdx
     19f: 0f 85 eb fe ff ff            	jne	-277 <_simd_ascii_print+0x90>
     1a5: 4d 85 c0                     	testq	%r8, %r8
     1a8: 0f 84 a8 00 00 00            	je	168 <_simd_ascii_print+0x256>
     1ae: c5 fa 7e 44 07 18            	vmovq	24(%rdi,%rax), %xmm0
     1b4: c5 f9 6f 0d 44 01 00 00      	vmovdqa	324(%rip), %xmm1
     1bc: c5 f9 fc c1                  	vpaddb	%xmm1, %xmm0, %xmm0
     1c0: c5 f9 6f 15 48 01 00 00      	vmovdqa	328(%rip), %xmm2
     1c8: c5 f9 de da                  	vpmaxub	%xmm2, %xmm0, %xmm3
     1cc: c5 f9 74 c3                  	vpcmpeqb	%xmm3, %xmm0, %xmm0
     1d0: c5 e1 76 db                  	vpcmpeqd	%xmm3, %xmm3, %xmm3
     1d4: c5 f9 ef c3                  	vpxor	%xmm3, %xmm0, %xmm0
     1d8: c4 e2 7d 31 c0               	vpmovzxbd	%xmm0, %ymm0
     1dd: c4 e2 7d 58 25 3a 01 00 00   	vpbroadcastd	314(%rip), %ymm4
     1e6: c5 fd db c4                  	vpand	%ymm4, %ymm0, %ymm0
     1ea: c5 25 db d8                  	vpand	%ymm0, %ymm11, %ymm11
     1ee: c5 fa 7e 44 07 10            	vmovq	16(%rdi,%rax), %xmm0
     1f4: c5 f9 fc c1                  	vpaddb	%xmm1, %xmm0, %xmm0
     1f8: c5 f9 de ea                  	vpmaxub	%xmm2, %xmm0, %xmm5
     1fc: c5 f9 74 c5                  	vpcmpeqb	%xmm5, %xmm0, %xmm0
     200: c5 f9 ef c3                  	vpxor	%xmm3, %xmm0, %xmm0
     204: c4 e2 7d 31 c0               	vpmovzxbd	%xmm0, %ymm0
     209: c5 fd db c4                  	vpand	%ymm4, %ymm0, %ymm0
     20d: c5 2d db d0                  	vpand	%ymm0, %ymm10, %ymm10
     211: c5 fa 7e 44 07 08            	vmovq	8(%rdi,%rax), %xmm0
     217: c5 f9 fc c1                  	vpaddb	%xmm1, %xmm0, %xmm0
     21b: c5 f9 de ea                  	vpmaxub	%xmm2, %xmm0, %xmm5
     21f: c5 f9 74 c5                  	vpcmpeqb	%xmm5, %xmm0, %xmm0
     223: c5 f9 ef c3                  	vpxor	%xmm3, %xmm0, %xmm0
     227: c4 e2 7d 31 c0               	vpmovzxbd	%xmm0, %ymm0
     22c: c5 fd db c4                  	vpand	%ymm4, %ymm0, %ymm0
     230: c5 35 db c8                  	vpand	%ymm0, %ymm9, %ymm9
     234: c5 fa 7e 04 07               	vmovq	(%rdi,%rax), %xmm0
     239: c5 f9 fc c1                  	vpaddb	%xmm1, %xmm0, %xmm0
     23d: c5 f9 de ca                  	vpmaxub	%xmm2, %xmm0, %xmm1
     241: c5 f9 74 c1                  	vpcmpeqb	%xmm1, %xmm0, %xmm0
     245: c5 f9 ef c3                  	vpxor	%xmm3, %xmm0, %xmm0
     249: c4 e2 7d 31 c0               	vpmovzxbd	%xmm0, %ymm0
     24e: c5 fd db c4                  	vpand	%ymm4, %ymm0, %ymm0
     252: c5 3d db c0                  	vpand	%ymm0, %ymm8, %ymm8
     256: c4 c1 35 db c3               	vpand	%ymm11, %ymm9, %ymm0
     25b: c4 c1 3d db ca               	vpand	%ymm10, %ymm8, %ymm1
     260: c5 f5 db c0                  	vpand	%ymm0, %ymm1, %ymm0
     264: c4 e3 7d 39 c1 01            	vextracti128	$1, %ymm0, %xmm1
     26a: c5 f9 db c1                  	vpand	%xmm1, %xmm0, %xmm0
     26e: c5 f9 70 c8 4e               	vpshufd	$78, %xmm0, %xmm1
     273: c5 f9 db c1                  	vpand	%xmm1, %xmm0, %xmm0
     277: c5 f9 70 c8 e5               	vpshufd	$229, %xmm0, %xmm1
     27c: c5 f9 db c1                  	vpand	%xmm1, %xmm0, %xmm0
     280: c5 f9 7e c0                  	vmovd	%xmm0, %eax
     284: 49 39 f1                     	cmpq	%rsi, %r9
     287: 74 21                        	je	33 <_simd_ascii_print+0x2aa>
     289: 0f 1f 80 00 00 00 00         	nopl	(%rax)
     290: 42 0f b6 14 0f               	movzbl	(%rdi,%r9), %edx
     295: 80 c2 e0                     	addb	$-32, %dl
     298: 31 c9                        	xorl	%ecx, %ecx
     29a: 80 fa 5f                     	cmpb	$95, %dl
     29d: 0f 92 c1                     	setb	%cl
     2a0: 21 c8                        	andl	%ecx, %eax
     2a2: 49 ff c1                     	incq	%r9
     2a5: 4c 39 ce                     	cmpq	%r9, %rsi
     2a8: 75 e6                        	jne	-26 <_simd_ascii_print+0x290>
     2aa: 5d                           	popq	%rbp
     2ab: c5 f8 77                     	vzeroupper
     2ae: c3                           	retq
     2af: c4 41 35 76 c9               	vpcmpeqd	%ymm9, %ymm9, %ymm9
     2b4: c5 7d 6f 05 24 00 00 00      	vmovdqa	36(%rip), %ymm8
     2bc: 31 c0                        	xorl	%eax, %eax
     2be: c4 41 2d 76 d2               	vpcmpeqd	%ymm10, %ymm10, %ymm10
     2c3: c4 41 25 76 db               	vpcmpeqd	%ymm11, %ymm11, %ymm11
     2c8: 4d 85 c0                     	testq	%r8, %r8
     2cb: 0f 85 dd fe ff ff            	jne	-291 <_simd_ascii_print+0x1ae>
     2d1: e9 80 ff ff ff               	jmp	-128 <_simd_ascii_print+0x256>
```

**Comment by achille-roussel** [comment]
That's a great suggestion, I'll give it a try. 

I'm still just starting to navigate assembly, so many tricks to learn :D

**Comment by achille-roussel** [comment]
I followed @chriso's recommendations and revisited the implementations, which yielded some nice results:

Comparison to the previous version:
```
name                                old time/op    new time/op    delta
ValidPrint/some_kind_of_long...       11.7ns ± 5%    10.5ns ± 3%  -10.60%  (p=0.008 n=5+5)
ValidPrint/some_kind_of_long...#01    9.05ns ± 1%    7.90ns ± 2%  -12.71%  (p=0.008 n=5+5)
ValidPrint/12345678901234567...        697ns ± 2%     379ns ± 2%  -45.64%  (p=0.008 n=5+5)
name                                old speed      new speed      delta
ValidPrint/some_kind_of_long...     4.46GB/s ± 5%  4.97GB/s ± 3%  +11.50%  (p=0.008 n=5+5)
ValidPrint/some_kind_of_long...#01  7.07GB/s ± 1%  8.11GB/s ± 2%  +14.61%  (p=0.008 n=5+5)
ValidPrint/12345678901234567...     14.3GB/s ± 2%  26.4GB/s ± 2%  +84.12%  (p=0.008 n=5+5)
```

Comparison to master:
```
name                                old time/op    new time/op     delta
ValidPrint/some_kind_of_long...       13.9ns ± 3%     10.5ns ± 3%   -24.75%  (p=0.008 n=5+5)
ValidPrint/some_kind_of_long...#01    13.5ns ± 1%      7.9ns ± 2%   -41.34%  (p=0.008 n=5+5)
ValidPrint/12345678901234567...       1.13µs ± 1%     0.38µs ± 2%   -66.39%  (p=0.008 n=5+5)
name                                old speed      new speed       delta
ValidPrint/some_kind_of_long...     3.74GB/s ± 3%   4.97GB/s ± 3%   +32.85%  (p=0.008 n=5+5)
ValidPrint/some_kind_of_long...#01  4.75GB/s ± 1%   8.11GB/s ± 2%   +70.63%  (p=0.008 n=5+5)
ValidPrint/12345678901234567...     8.87GB/s ± 2%  26.41GB/s ± 2%  +197.80%  (p=0.008 n=5+5)
```

**Review by chriso — APPROVED** [review]

**Pull request merged**
